#Astatine Online
world_setting:
  motd: 'ASTATINE ONLINE'
  minelist: 'https://minelist.kr/servers/astn.kr'
  discord: 'https://discord.com/invite/k6dyKDsuZq'
  notion: 'https://jaxple.notion.site/Astn-kr-e000a5d52aaa4611a63fd62629ea0f36?pvs=4'
message:
  commandHelp: '[/help] : /명령어, /서버팁, /커뮤니티'
  commandCommunity: '/커뮤니티'
  mineListVote: '[클릭] > 마인리스트 추천'
  discordInvite: '[클릭] > 디스코드 참가'
  serverGuideNotion: '[클릭] > 서버 플레이 가이드'
  commandServerTip: '/tip'
  steelLifeTip: '플레이어 사살시 체력을 약탈합니다. [최대 60, 최소 4칸]'
  raidTip: '습격 발생시 해당 좌표 지점이 공지됩니다.'
  weaponTip: '근접무기를 양손에 들시 공격 속도가 매우 빨라 집니다.'
  explosiveTip: '모든 기존의 폭팔을 조심하세요. 크리퍼, 가스트, 위더, TNT 모든게 "매우" 위험 합니다.'
  CommandTip: '/명령어'
  commandFly: '/fly - 플라이는 항상 활성화 되어 있으며 필요시 입력해주세요.'
  commandHat: '/hat - 손에 든 아이템을 머리에 씁니다.'
  commandSwap: '/swap - 손에 든 아이템을 다른 손으로 옮깁니다.'
  commandTotem: '/totem - 인벤토리의 토템을 모두 합칩니다.'
  commandEnhance: '/강화 - 강화창을 열거나 닫습니다.'
  commandAnnouncing: '/공지 - 공지사항 채팅을 끄거나 킵니다.'
  commandTpa: '/tpa, /tpahere, /tpatoggle - tpa를 사용합니다.'
